### ISSUE TITLE
php 8.4 - incompatibility

### ISSUE THREAD

**Issue by logic-b-o-m-b** [laravel/pint#310] opened 2024-11-28 12:43 UTC
### Pint Version

1.18.3

### PHP Version

8.4.x

### Description

I did not try pint with property hooks, or updated exit() / die() but they for sure cause issues to pint as well.

### Steps To Reproduce

Create following class and try to pass it by pint.

```php 
class Example
{
    public function __construct(
        public private(set) ?string $text = null;
    ) {
        $this->text ??= 'Hello World!';
    }
}
```
_Result:_ Fatal error: Multiple access type modifiers are not allowed on line XX

After removing redundant "public":

```php 
class Example
{
    public function __construct(
        private(set) ?string $text = null;
    ) {
        $this->text ??= 'Hello World!';
    }
}
```
_Result_:  Parse error: syntax error, unexpected token ")", expecting amp on line XX

**Comment by logic-b-o-m-b** [comment] 2024-11-29 22:08
thank you @Jubeki

**Comment by crynobone** [comment] 2024-12-02 01:53
Duplicate of https://github.com/laravel/pint/pull/304 

Let's just monitor the status using the posted PR.

**Closed by crynobone** 2024-12-02 01:53 UTC
