### ISSUE TITLE
Perhaps, Would be better for Pint to support blade file

### ISSUE THREAD

**Issue by nmfirdausw** [laravel/pint#203] opened 2023-08-04 18:20 UTC
I was using folio and livewire volt.
I was able to style file in resources/views when change file extension from blade.php to php.
Would be better if pint can support blade file also.

```
-use function Livewire\Volt\{state, rules, mount, boot, on};
  +use function Livewire\Volt\boot;
  +use function Livewire\Volt\mount;
  +use function Livewire\Volt\on;
  +use function Livewire\Volt\rules;
  +use function Livewire\Volt\state;
```

Hope for pint also ignore and not refactor [[ use function Livewire\Volt\{state, rules, mount, boot, on}; ]] also.

**Comment by crynobone** [comment] 2023-08-05 08:05
Duplicate of #64

**Closed by crynobone** 2023-08-05 08:05 UTC
