### ISSUE TITLE
Laravel Pint does not support class properties in interfaces with PHP 8.4

### ISSUE THREAD

**Issue by martio** [laravel/pint#314] opened 2024-12-07 04:28 UTC
### Pint Version

1.18.3

### PHP Version

8.4.1

### Description

I encountered an issue with Laravel Pint when using PHP 8.4. Specifically, Laravel Pint is unable to handle class properties defined in interfaces, which is a new feature in PHP 8.4.

<img width="1509" alt="Error" src="https://github.com/user-attachments/assets/2b0118d4-92c9-49f1-8905-09329ef9f40a">

### Steps To Reproduce

Steps to Reproduce:

1. Use PHP 8.4 and create an interface with class properties:

```php
interface Identifiable
{
    public Uid $aggregateIdentifier { get; }
}
```

2. Implement the interface in a class and define a property getter:

```php
class User implements Identifiable
{
    public Uid $aggregateIdentifier {
        get => $this->userId;
    }
}
```

3. Run Laravel Pint.

**Comment by crynobone** [comment] 2024-12-09 02:01
Duplicate of https://github.com/laravel/pint/pull/304 

Let's just monitor the status using the posted PR.

**Closed by crynobone** 2024-12-09 02:01 UTC
