### ISSUE TITLE
syntax error, unexpected token "="

### ISSUE THREAD

**Issue by mdinopol** [laravel/pint#246] opened 2024-01-22 08:32 UTC
### Pint Version

1.13

### PHP Version

8.2

### Description

When running `./vendor/bin/pint`, it fails on some built in config files such as `config/broadcasting.php` while I haven't even touched a thing in that file.

### Steps To Reproduce

Here is my `pint.json` configuration:

```
{
    "preset": "laravel",
    "rules": {
        "class_attributes_separation": {
            "elements": {
                "const": "none",
                "method": "one",
                "property": "one",
                "trait_import": "none",
                "case": "none"
            }
        },
        "no_superfluous_phpdoc_tags": false,
        "compact_nullable_typehint": true,
        "list_syntax": {
            "syntax": "short"
        },
        "no_null_property_initialization": true,
        "no_superfluous_elseif": true,
        "no_useless_else": true,
        "ordered_class_elements": true,
        "simplified_null_return": true,
        "yoda_style": false,
        "single_line_throw": false,
        "binary_operator_spaces": {
            "operators": {
                "=": "align_single_space_minimal",
                "=>": "align_single_space_minimal"
            }
        }
    },
    "path": [
        "app",
        "config",
        "database",
        "routes",
        "tests"
    ],
    "notPath": [
        "application/views"
    ],
    "name": [
        "*.php"
    ],
    "ignoreDotFiles": true,
    "ignoreVCS": true
}

```

**Comment by Jubeki** [comment] 2024-01-22 08:34
Duplicate of #245

Is already fixed, will probably be released on Tuesday.
You can for now revert to 1.13.8

**Comment by driesvints** [comment] 2024-01-22 09:02
Thanks @Jubeki

**Closed by driesvints** 2024-01-22 09:02 UTC
