### ISSUE TITLE
Warning Deprecated when run ./vendor/bin/pint

### ISSUE THREAD

**Issue by yanbrasiliano** [laravel/pint#316] opened 2024-12-10 19:25 UTC
### Pint Version

1.18.3

### PHP Version

8.4.1

### Description

This is a question, not a bug (maybe).
I'm running pint to standardize my project and when I apply it, it gives me the warnings below, but my application is all up-to-date and this seems to me to be deprecations of third-party packages. Is this common? Is there a solution or is it a lack of compatibility with the php version? 

The warnings: 

```
Deprecated: optional(): Implicitly marking parameter $callback as nullable is deprecated, the explicit nullable type must be used instead in phar:///var/www/html/vendor/laravel/pint/builds/pint/vendor/illuminate/support/helpers.php on line 190

Deprecated: with(): Implicitly marking parameter $callback as nullable is deprecated, the explicit nullable type must be used instead in phar:///var/www/html/vendor/laravel/pint/builds/pint/vendor/illuminate/support/helpers.php on line 430

Deprecated: Illuminate\Container\Container::beforeResolving(): Implicitly marking parameter $callback as nullable is deprecated, the explicit nullable type must be used instead in phar:///var/www/html/vendor/laravel/pint/builds/pint/vendor/illuminate/container/Container.php on line 1151

Deprecated: Illuminate\Container\Container::resolving(): Implicitly marking parameter $callback as nullable is deprecated, the explicit nullable type must be used instead in phar:///var/www/html/vendor/laravel/pint/builds/pint/vendor/illuminate/container/Container.php on line 1171

Deprecated: Illuminate\Container\Container::afterResolving(): Implicitly marking parameter $callback as nullable is deprecated, the explicit nullable type must be used instead in phar:///var/www/html/vendor/laravel/pint/builds/pint/vendor/illuminate/container/Container.php on line 1191

Deprecated: Illuminate\Container\Container::setInstance(): Implicitly marking parameter $container as nullable is deprecated, the explicit nullable type must be used instead in phar:///var/www/html/vendor/laravel/pint/builds/pint/vendor/illuminate/container/Container.php on line 1430

Deprecated: Illuminate\Contracts\Container\Container::beforeResolving(): Implicitly marking parameter $callback as nullable is deprecated, the explicit nullable type must be used instead in phar:///var/www/html/vendor/laravel/pint/builds/pint/vendor/illuminate/contracts/Container/Container.php on line 200

Deprecated: Illuminate\Contracts\Container\Container::resolving(): Implicitly marking parameter $callback as nullable is deprecated, the explicit nullable type must be used instead in phar:///var/www/html/vendor/laravel/pint/builds/pint/vendor/illuminate/contracts/Container/Container.php on line 209

Deprecated: Illuminate\Contracts\Container\Container::afterResolving(): Implicitly marking parameter $callback as nullable is deprecated, the explicit nullable type must be used instead in phar:///var/www/html/vendor/laravel/pint/builds/pint/vendor/illuminate/contracts/Container/Container.php on line 218

Deprecated: Illuminate\Support\Traits\Conditionable::when(): Implicitly marking parameter $callback as nullable is deprecated, the explicit nullable type must be used instead in phar:///var/www/html/vendor/laravel/pint/builds/pint/vendor/illuminate/conditionable/Traits/Conditionable.php on line 21

Deprecated: Illuminate\Support\Traits\Conditionable::when(): Implicitly marking parameter $default as nullable is deprecated, the explicit nullable type must be used instead in phar:///var/www/html/vendor/laravel/pint/builds/pint/vendor/illuminate/conditionable/Traits/Conditionable.php on line 21

Deprecated: Illuminate\Support\Traits\Conditionable::unless(): Implicitly marking parameter $callback as nullable is deprecated, the explicit nullable type must be used instead in phar:///var/www/html/vendor/laravel/pint/builds/pint/vendor/illuminate/conditionable/Traits/Conditionable.php on line 53

Deprecated: Illuminate\Support\Traits\Conditionable::unless(): Implicitly marking parameter $default as nullable is deprecated, the explicit nullable type must be used instead in phar:///var/www/html/vendor/laravel/pint/builds/pint/vendor/illuminate/conditionable/Traits/Conditionable.php on line 53

Deprecated: Illuminate\Support\Arr::first(): Implicitly marking parameter $callback as nullable is deprecated, the explicit nullable type must be used instead in phar:///var/www/html/vendor/laravel/pint/builds/pint/vendor/illuminate/collections/Arr.php on line 188

Deprecated: Illuminate\Support\Arr::last(): Implicitly marking parameter $callback as nullable is deprecated, the explicit nullable type must be used instead in phar:///var/www/html/vendor/laravel/pint/builds/pint/vendor/illuminate/collections/Arr.php on line 219

Deprecated: Illuminate\Events\Dispatcher::__construct(): Implicitly marking parameter $container as nullable is deprecated, the explicit nullable type must be used instead in phar:///var/www/html/vendor/laravel/pint/builds/pint/vendor/illuminate/events/Dispatcher.php on line 75

```

### Steps To Reproduce

1. Run ./vendor/bin/pint
2. Observe the terminal and the warnings output;

**Comment by crynobone** [comment] 2024-12-10 23:05
Duplicate of https://github.com/laravel/pint/pull/304 

Let's just monitor the status using the posted PR.

**Closed by crynobone** 2024-12-10 23:05 UTC
